In [1]:
import numpy as np
import pandas as pd
import re
import sklearn
import nltk
from nltk.corpus import stopwords

In [2]:
data = pd.read_csv(r"C:\Users\dines\Downloads\Text_preprecessing_and_Creating_logistic_regrestion.ipynb")

In [3]:
df = data.copy()

In [4]:
df=df.drop("Unnamed: 0", axis =1)

## Converting into lower case

In [5]:
def lowercase(text):
    return text.str.lower()

df['review'] = lowercase(df['review'])
df['review']

0       very very good ..i really appreciate vegga for...
1       good for day to day use and for those who driv...
2       value added product for money:light weight ove...
3       worth the pricebought for ₹860pros:- a lot of ...
4       well i got this helmet literally for free.. as...
                              ...                        
5933          nice one ,it's meet my expectationread more
5934    lovely...i fell very comfortable in this helme...
5935    helmet material is of good quality. i have use...
5936                                     perfectread more
5937         better to go for studd or steelbirdread more
Name: review, Length: 5938, dtype: object

## Removehtmltags

In [6]:
def removehtmltags(text):
    return re.sub(r'<.*?>','',text)
    
df['review']= df['review'].apply(removehtmltags)
df['review']

0       very very good ..i really appreciate vegga for...
1       good for day to day use and for those who driv...
2       value added product for money:light weight ove...
3       worth the pricebought for ₹860pros:- a lot of ...
4       well i got this helmet literally for free.. as...
                              ...                        
5933          nice one ,it's meet my expectationread more
5934    lovely...i fell very comfortable in this helme...
5935    helmet material is of good quality. i have use...
5936                                     perfectread more
5937         better to go for studd or steelbirdread more
Name: review, Length: 5938, dtype: object

## Remove Urls

In [7]:
def removeurls(text):
    return re.sub('http?s://\s+|www\.s\+', " ", text)

df['review'] = df['review'].apply(removeurls)
df['review']

0       very very good ..i really appreciate vegga for...
1       good for day to day use and for those who driv...
2       value added product for money:light weight ove...
3       worth the pricebought for ₹860pros:- a lot of ...
4       well i got this helmet literally for free.. as...
                              ...                        
5933          nice one ,it's meet my expectationread more
5934    lovely...i fell very comfortable in this helme...
5935    helmet material is of good quality. i have use...
5936                                     perfectread more
5937         better to go for studd or steelbirdread more
Name: review, Length: 5938, dtype: object

## handle new line

In [8]:
def handlenewline(text):
    return re.sub('\n|\r'," ", text)
df["review"] = df['review'].apply(handlenewline)

## removing read me

In [9]:
def removereadme(text):
    return re.sub('READ ME','',text)
df['return'] = df['review'].apply(removereadme)

## remove special charecters/punctuations

In [10]:
def removespecialchars(text):
    return re.sub('[^0-9a-zA-Z]'," ",text)
df['review'] = df['review'].apply(removespecialchars)


## remove stop words

In [11]:
 nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Ravi
[nltk_data]     Kumar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [12]:
def removestopwords(text):

    a = []
    for word in text.split(' '):
        if word not in stopwords.words('english'):
            a.append(word)
    return ' '.join(a)

In [13]:
df['review'] = df['review'].apply(removestopwords)
df.head()

review  rating  \
0  good   really appreciate vegga helmet  cheap p...       5   
1  good day day use drives safely  quality good  ...       4   
2  value added product money light weight head ma...       5   
3  worth pricebought  860pros   lot space glass f...       4   
4  well got helmet literally free   flipkart plus...       5   

                                              return  
0  very very good ..i really appreciate vegga for...  
1  good for day to day use and for those who driv...  
2  value added product for money:light weight ove...  
3  worth the pricebought for ₹860pros:- a lot of ...  
4  well i got this helmet literally for free.. as...

In [14]:
df=df.drop("return", axis =1)

## convert tokens

In [15]:
def converttokens(data, colName):
    x= colName + "_wordTokens"
    data[x] = data[colName].str.split(' ')

In [16]:
converttokens(df, 'review')

In [17]:
df

review  rating  \
0     good   really appreciate vegga helmet  cheap p...       5   
1     good day day use drives safely  quality good  ...       4   
2     value added product money light weight head ma...       5   
3     worth pricebought  860pros   lot space glass f...       4   
4     well got helmet literally free   flipkart plus...       5   
...                                                 ...     ...   
5933                     nice one  meet expectationread       3   
5934            lovely   fell comfortable helmet   read       1   
5935  helmet material good quality  used 6 months  n...       5   
5936                                        perfectread       5   
5937                      better go studd steelbirdread       4   

                                      review_wordTokens  
0     [good, , , really, appreciate, vegga, helmet, ...  
1     [good, day, day, use, drives, safely, , qualit...  
2     [value, added, product, money, light, weight, ...  
3     [worth, pricebought, , 860pros, , , lot, space...  
4     [well, got, helmet, literally, free, , , flipk...  
...                                                 ...  
5933               [nice, one, , meet, expectationread]  
5934  [lovely, , , fell, comfortable, helmet, , , read]  
5935  [helmet, material, good, quality, , used, 6, m...  
5936                                      [perfectread]  
5937                 [better, go, studd, steelbirdread]  

[5938 rows x 3 columns]

## lemmatization

In [18]:
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
lem = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to C:\Users\Ravi
[nltk_data]     Kumar\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\Ravi
[nltk_data]     Kumar\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [19]:
def lemTokens(text):
    lemTokens = []
    for word in text.split(' '):
        
        if word != ' ' or word !='':
            lemTokens.append(lem.lemmatize(word))
    return lemTokens

In [20]:
df["lemTokens"] = df["review"].apply(lemTokens)

In [21]:
df.head()

review  rating  \
0  good   really appreciate vegga helmet  cheap p...       5   
1  good day day use drives safely  quality good  ...       4   
2  value added product money light weight head ma...       5   
3  worth pricebought  860pros   lot space glass f...       4   
4  well got helmet literally free   flipkart plus...       5   

                                   review_wordTokens  \
0  [good, , , really, appreciate, vegga, helmet, ...   
1  [good, day, day, use, drives, safely, , qualit...   
2  [value, added, product, money, light, weight, ...   
3  [worth, pricebought, , 860pros, , , lot, space...   
4  [well, got, helmet, literally, free, , , flipk...   

                                           lemTokens  
0  [good, , , really, appreciate, vegga, helmet, ...  
1  [good, day, day, use, drive, safely, , quality...  
2  [value, added, product, money, light, weight, ...  
3  [worth, pricebought, , 860pros, , , lot, space...  
4  [well, got, helmet, literally, free, , , flipk...

## converting lem tokens into lem sentence

In [22]:
df["lemSentences"] = df["lemTokens"].str.join(' ')

In [23]:
df

review  rating  \
0     good   really appreciate vegga helmet  cheap p...       5   
1     good day day use drives safely  quality good  ...       4   
2     value added product money light weight head ma...       5   
3     worth pricebought  860pros   lot space glass f...       4   
4     well got helmet literally free   flipkart plus...       5   
...                                                 ...     ...   
5933                     nice one  meet expectationread       3   
5934            lovely   fell comfortable helmet   read       1   
5935  helmet material good quality  used 6 months  n...       5   
5936                                        perfectread       5   
5937                      better go studd steelbirdread       4   

                                      review_wordTokens  \
0     [good, , , really, appreciate, vegga, helmet, ...   
1     [good, day, day, use, drives, safely, , qualit...   
2     [value, added, product, money, light, weight, ...   
3     [worth, pricebought, , 860pros, , , lot, space...   
4     [well, got, helmet, literally, free, , , flipk...   
...                                                 ...   
5933               [nice, one, , meet, expectationread]   
5934  [lovely, , , fell, comfortable, helmet, , , read]   
5935  [helmet, material, good, quality, , used, 6, m...   
5936                                      [perfectread]   
5937                 [better, go, studd, steelbirdread]   

                                              lemTokens  \
0     [good, , , really, appreciate, vegga, helmet, ...   
1     [good, day, day, use, drive, safely, , quality...   
2     [value, added, product, money, light, weight, ...   
3     [worth, pricebought, , 860pros, , , lot, space...   
4     [well, got, helmet, literally, free, , , flipk...   
...                                                 ...   
5933               [nice, one, , meet, expectationread]   
5934  [lovely, , , fell, comfortable, helmet, , , read]   
5935  [helmet, material, good, quality, , used, 6, m...   
5936                                      [perfectread]   
5937                 [better, go, studd, steelbirdread]   

                                           lemSentences  
0     good   really appreciate vegga helmet  cheap p...  
1     good day day use drive safely  quality good  l...  
2     value added product money light weight head ma...  
3     worth pricebought  860pros   lot space glass f...  
4     well got helmet literally free   flipkart plus...  
...                                                 ...  
5933                     nice one  meet expectationread  
5934            lovely   fell comfortable helmet   read  
5935  helmet material good quality  used 6 month  ni...  
5936                                        perfectread  
5937                      better go studd steelbirdread  

[5938 rows x 5 columns]

## splitting data into train and test

In [24]:
import sklearn 
from sklearn.model_selection import train_test_split

In [25]:
x = df[['lemSentences']]
y = df[['rating']]

In [26]:
xTrain,xTest,yTrain,yTest = train_test_split(x,y,
                                            test_size =0.2)


xTrain.shape, xTest.shape, len(yTrain), len(yTest)

((4750, 1), (1188, 1), 4750, 1188)

## creating a model for count vectorizer

### for bag of unigrams

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
countvectorizer=CountVectorizer()

In [30]:
countXTrain=countvectorizer.fit_transform(xTrain["lemSentences"])

In [32]:
countXTrain

<4750x2828 sparse matrix of type '<class 'numpy.int64'>'
	with 21509 stored elements in Compressed Sparse Row format>

In [34]:
countXTest=countvectorizer.transform(xTest["lemSentences"])

In [35]:
countXTest

<1188x2828 sparse matrix of type '<class 'numpy.int64'>'
	with 5040 stored elements in Compressed Sparse Row format>

## creating a logistic regression model

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score as acs
from sklearn.metrics import confusion_matrix

LR = LogisticRegression()


In [37]:
LR.fit(countXTrain,yTrain)

C:\Users\Ravi Kumar\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ravi Kumar\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [38]:
YTrainpred=LR.predict(countXTrain)
YTestpred=LR.predict(countXTest)

In [39]:
acs(yTrain,YTrainpred),acs(yTest,YTestpred)

(0.7063157894736842, 0.5707070707070707)

In [40]:
confusion_matrix(yTrain,YTrainpred),confusion_matrix(yTest,YTestpred)

(array([[  11,    0,    0,    1,   54],
        [   0,    4,    2,    1,   51],
        [   0,    0,   78,   18,  393],
        [   1,    0,    2,  468,  829],
        [   0,    0,    1,   42, 2794]], dtype=int64),
 array([[  0,   0,   0,   0,  12],
        [  0,   0,   0,   0,  20],
        [  0,   0,   1,   7,  95],
        [  0,   0,   3,  27, 304],
        [  0,   0,   2,  67, 650]], dtype=int64))

## for bag of uni - bi grams

In [41]:
countvectorizer=CountVectorizer(ngram_range=(1,2))

bixTrain=countvectorizer.fit_transform(xTrain["lemSentences"])
bixTrain.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [42]:
bixTest=countvectorizer.transform(xTest["lemSentences"])
bixTest.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## creating a logistic regression model

In [43]:
LR.fit(bixTrain,yTrain)

YTrainpred=LR.predict(bixTrain)
YTestpred=LR.predict(bixTest)

C:\Users\Ravi Kumar\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ravi Kumar\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [44]:
# checking the accuracy score and confusion matrix

acs(yTrain,YTrainpred),acs(yTest,YTestpred)

(0.8227368421052632, 0.5521885521885522)

In [45]:
confusion_matrix(yTrain,YTrainpred),confusion_matrix(yTest,YTestpred)

(array([[  18,    0,    0,    6,   42],
        [   0,   12,    0,    2,   44],
        [   0,    0,  243,   22,  224],
        [   0,    0,    2,  840,  458],
        [   0,    0,    0,   42, 2795]], dtype=int64),
 array([[  0,   0,   0,   1,  11],
        [  0,   0,   0,   0,  20],
        [  0,   0,   1,  11,  91],
        [  0,   0,   1,  30, 303],
        [  0,   0,   6,  88, 625]], dtype=int64))

## creating a mode for tfidfvectorizer

### for tfidf bag of uni grams

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()

tfunixTrain=tfidf.fit_transform(xTrain["lemSentences"])
tfunixTrain.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [47]:
tfunixTest=tfidf.transform(xTest["lemSentences"])
tfunixTest.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## creating a logistic regression model

In [48]:
LR.fit(tfunixTrain,yTrain)

YTrainpred=LR.predict(tfunixTrain)
YTestpred=LR.predict(tfunixTest)

C:\Users\Ravi Kumar\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [49]:
# checking the accuracy score and confusion matrix

acs(yTrain,YTrainpred),acs(yTest,YTestpred)

(0.6385263157894737, 0.5925925925925926)

In [50]:
confusion_matrix(yTrain,YTrainpred),confusion_matrix(yTest,YTestpred)

(array([[   0,    0,    0,    2,   64],
        [   0,    0,    0,    3,   55],
        [   0,    0,    2,   16,  471],
        [   0,    0,    0,  218, 1082],
        [   0,    0,    0,   24, 2813]], dtype=int64),
 array([[  0,   0,   0,   0,  12],
        [  0,   0,   0,   0,  20],
        [  0,   0,   0,   5,  98],
        [  0,   0,   0,  15, 319],
        [  0,   0,   0,  30, 689]], dtype=int64))

## tfidf bag of uni - bi grams

In [52]:
tfuni_biVec=TfidfVectorizer(ngram_range = (1,2))

tfbixTrain=tfuni_biVec.fit_transform(xTrain["lemSentences"])
tfbixTrain.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [54]:
tfbixTest=tfuni_biVec.transform(xTrain["lemSentences"])
tfbixTest.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## creating a logistic regression model

In [55]:
LR.fit(tfbixTrain,yTrain)

yTrainpred=LR.predict(tfbixTrain)
yTestpred=LR.predict(tfbixTest)

C:\Users\Ravi Kumar\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [56]:
acs(yTrain,yTrainpred)

0.6795789473684211

In [57]:
confusion_matrix(yTrain,YTrainpred)

array([[   0,    0,    0,    2,   64],
       [   0,    0,    0,    3,   55],
       [   0,    0,    2,   16,  471],
       [   0,    0,    0,  218, 1082],
       [   0,    0,    0,   24, 2813]], dtype=int64)